version: '2'

services:
  mariadb:
    container_name: mariadb
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami/
      - ./db_entrypoint/:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  prestashop:
    container_name: prestashop
    image: 'bitnami/prestashop:1.7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_USER=root
      - PRESTASHOP_DATABASE_NAME=prestashop
      - ALLOW_EMPTY_PASSWORD=yes
      - PRESTASHOP_COUNTRY=pl
      - PRESTASHOP_LANGUAGE=pl
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - prestashop_data:/bitnami/prestashop/
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
