<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOikw7nm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOikw7nm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOikw7nm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOikw7nm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOikw7nm\appProdProjectContainer([
    'container.build_hash' => 'Oikw7nm',
    'container.build_id' => '50e2ca9e',
    'container.build_time' => 1573380080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOikw7nm');
