<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWmqvsub\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWmqvsub/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWmqvsub.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWmqvsub\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWmqvsub\appProdProjectContainer([
    'container.build_hash' => 'Wmqvsub',
    'container.build_id' => '5f0b0b30',
    'container.build_time' => 1575444694,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWmqvsub');
